// export const API_KEY = "Rlivcvu8LqidxlnDZlg5d1dGFL5N4p95"
export const API_KEY = "9WNZsVTjUH7OfCV8vCmWir9rnGELFggu"
export const CURRENT_WEATHER_URI = "https://dataservice.accuweather.com/currentconditions/v1/"
export const CITY_URI = "https://dataservice.accuweather.com/locations/v1/cities/autocomplete?"
export const DAILY_FORECASTS_URI = "https://dataservice.accuweather.com/forecasts/v1/daily/5day/"
export const CURRENT_LOCATION_GEOPOSITION_URI = "https://dataservice.accuweather.com/locations/v1/cities/geoposition/search" 