
//ACCUWEATHER API
export const DEFAULT_LOAD_WEATHER = 'DEFAULT_LOAD_WEATHER';
export const AUTO_COMPLETE = 'AUTO_COMPLETE';
export const DAILY_FORECASTS = 'DAILY_FORECASTS';

//Geolocation API and ACCUWEATHER API
export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION';


//LOCAL DATA UPDATE
export const CHANGE_UNIT_DEGREES = 'CHANGE_UNIT_DEGREES';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const UPDATE_CITY_NAME = 'UPDATE_CITY_NAME';
export const CURRENT_WEATHER_FROM_FAVORITES = 'CURRENT_WEATHER_FROM_FAVORITES';