export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION';
export const INPUT_TEXT = 'INPUT_TEXT';
export const DEFAULT_LOAD_WEATHER = 'DEFAULT_LOAD_WEATHER';
export const AUTO_COMPLETE = 'AUTO_COMPLETE';
export const DAILY_FORECASTS = 'DAILY_FORECASTS';